test: Use 1 instead of true
Building in RHEL 10.0 failed:

    /home/test/librepo/examples/c/download_repos_parallel.c: In function ‘create_handle’:
    /home/test/librepo/examples/c/download_repos_parallel.c:52:48: error: ‘true’ undeclared (first use in this function)
       52 |   lr_handle_setopt(h, NULL, LRO_INTERRUPTIBLE, true);
          |                                                ^~~~

true is not implicitly defined until ISO C23.

This patch fixes it by using a numerical value, similar to commit
0dae97aafc4d0112cc192dd6c9b74687342431f5 ("Use 0 instead of `false` for
assert").