downloader: Report last error
I'm seeing a corrupted RPM in an available repository.  Even when
just using `baseurl=` for the one server, librepo drops into
internal mirorring machinery during downloads and just reports:

```
error: Cannot download bash-4.3.33-2.fc22.x86_64.rpm: All mirrors were tried
```

Which isn't very useful.  Let's cache the last error we hit, so we can
instead say:

```
error: Cannot download bash-4.3.33-2.fc22.x86_64.rpm: All mirrors were tried.  Last error: Downloading successful, but checksum doesn't match. Calculated: 75d062b11bc74d345a6b51620f14c86dc232afa8e0fc6dad28479c0e97cb1d4f(sha256)  Expected: 21b27d1a5b80b933c1e142367624465b5e45163404f85ac2afed01efe260f91e(sha256)
```

(This error message could still be better, but one thing at a time)