tests: Adapt to CURL without NTLM support
If CURL is built without NTLM support (e.g. if libcurl-minimal RPM
package is installed instead of libcurl on Fedora),
tests/test_handle.c failed:

    /home/test/librepo/tests/test_handle.c:61:F:Main:test_handle:0: Assertion 'lr_handle_setopt(h, ((void *)0), LRO_HTTPAUTHMETHODS, LR_AUTH_NTLM)' failed

The cause is that the test exhibing NTLM authentication also checks that
lr_handle_setopt() succeeds.

This patch stops checking a return value of lr_handle_setopt() in case
of LR_AUTH_NTLM because a meaning of the test is checking for memory
leaks.

A similar issue was in python/tests/test_handle.py:

    ERROR: test_handle_setget_attr (tests.test_handle.TestCaseHandle.test_handle_setget_attr)
    No exception should be raised.
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/test/librepo/tests/python/tests/test_handle.py", line 477, in test_handle_setget_attr
	h.httpauthmethods = librepo.LR_AUTH_NTLM
	^^^^^^^^^^^^^^^^^
      File "/home/test/librepo/redhat-linux-build/librepo/python/librepo/__init__.py", line 1537, in __setattr__
	self.setopt(ATTR_TO_LRO[attr], val)
	~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/test/librepo/redhat-linux-build/librepo/python/librepo/__init__.py", line 1529, in setopt
	_librepo.Handle.setopt(self, option, val)
	~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
    librepo.LibrepoException: (8, 'curl error: A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.', 'An Curl handle error')

This patch ignores excpetions with that error message. (I did not find a way of
accessing fields of exception value directly.)